<?php $key = $this->helper('\Digitalriver\DrPay\Helper\Data')->getConfig('dr_settings/config/public_key');?>
<script type="text/javascript">
	function drKlarnaLoader(){
		var digitalriverjs = new DigitalRiver("<?php echo $key?>");
		if(typeof digitalriverjs != "undefined"){ //If url and key set in admin
			//loadScriptKlarna(jsUrl, function(){	
		    //After append js set Your API Key and Start DigitalRiver.js
		    var drklarnajs = digitalriverjs;
			// Create a token or display an error when the form is submitted.
			var paymentForm = document.getElementById('drpay-klarna-btn');
				paymentForm.addEventListener('click', function(event) {
				event.preventDefault();
				var payload = {};
				//After submit the creditcard details create the cart
	            jQuery.ajax({
					type: 'POST',
					url: BASE_URL + 'drpay/klarna/savedrquote',
					showLoader: true, //use for display loader 
					success: function (response) {
						//console.log(response);
						if (response.success) {
							if(response.content.payload){
								//Update billing address if not updated
								//jQuery(".checkout-billing-address .action-update").trigger("click");
								//once cart created get the payment source id
								var klarnaData = response.content.payload;
								drklarnajs.createSource(klarnaData).then(function(result) {
								    if (result.error) {
								        console.log(result.error);
										//Something went wrong, display the error message to the customer
										document.getElementById('message').innerHTML ="";
										document.getElementById('message').innerHTML =result.error;								        
										document.getElementById('klarna-message').innerHTML ="";
										document.getElementById('klarna-message').innerHTML =result.error;								        
								    } else {
								        var source = result.source;
								        //console.log(source);
        						        window.checkoutConfig.payment.drpay_klarna.redirect_url = source.redirect.redirectUrl;
        						        continueKlarnaOrder();
								        //send source to back end
								       // sendToBackend(source);
								    }
								});
							}
						}else{
							//Show Error Message
							console.log(response);
							//Something went wrong, display the error message to the customer
							document.getElementById('message').innerHTML = "";
							document.getElementById('message').innerHTML = response.content;
							document.getElementById('klarna-message').innerHTML = "";
							document.getElementById('klarna-message').innerHTML = response.content;
						}
					},
				});	
			});			    
		//});
		}
	}

	function continueKlarnaOrder()
	{
		require(["jquery"], function ($) {		
			var edit = '<?php echo $block->escapeJs($block->escapeHtml(__('Edit')));?>';
			var title = "<div class='title'>"+$(".payment-methods .payment-group .payment-method._active .payment-method-title .label span").html()+"</div>";
			var editlink = "<a class='payment-edit' href='javascript:void(0)' id='payment-edit-klarna' onclick='displayKlarnaForm()'>"+edit+"</a>";
			$("#payment-data_klarna").html(title+editlink);						
			$("#payment-data_klarna").css("display","block");
			$("#payment-data_klarna").addClass('payment-active');
			$(".klarna-btn-first").css("display","none");
			$(".klarna-btn-second").css("display","block");
			$(".klarna-btn-second .checkout").css("display","block");
			$(".payment-methods .payment-group .step-title").css("display","none");
			$(".payment-method._active .payment-method-content .payment-method-note").css("display","none");
			$(".payment-methods .payment-group .payment-method .payment-method-title").css("display","none");
			$(".payment-methods .payment-group .payment-method .details").css("display","none");
			$(".payment-methods .payment-group .payment-method .payment-logos").css("display","none");
			$(".payment-methods .payment-group .payment-method .payment-icon").css("display","none");
			$(".payment-methods .payment-group .payment-method .payment-method-instruction").css("display","none");
			$("#payframe").css("display","none");
			$('.checkout-tabs .nav-pills li').removeClass('active');
			$('.checkout-tabs .nav-pills li:nth-child(2)').addClass('active');
			$('.step-content').css('background','#e6e6e6');
			$('.payment-method-content').css('margin-bottom','50px');
			if(window.checkoutConfig.quoteData.is_virtual){
				$(".billing-address-details .action-edit-address").css("display","none");
			}else{				
				$(".billing-address-details .action-edit-address").css("display","none");
				$(".payment-method-billing-address .billing-address-same-as-shipping-block").css("display","none");
			}
		});		
	}	
	function displayKlarnaForm(){
		jQuery(".payment-methods .payment-group .step-title").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .payment-method-title").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .details").css("display","inline-block");
		jQuery(".payment-methods .payment-group .payment-method .payment-logos").css("display","inline-block");
		jQuery(".payment-methods .payment-group .payment-method .payment-icon").css("display","inline-block");
		jQuery("#drpay-klarna-form").css("display","block");
		jQuery("#payment-data_klarna").css("display","none");
		jQuery("#payment-data_klarna").removeClass('payment-active');
		jQuery(".payment-methods .payment-group .payment-method .payment-method-instruction").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .payment-method-content .checkout").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .klarna-btn-first").css("display","block");
		 jQuery(".payment-methods .payment-group .payment-method .klarna-btn-first .checkout").css("display","block");
		jQuery('.checkout-tabs .nav-pills li').removeClass('active');
		jQuery('.checkout-tabs .nav-pills li:nth-child(1)').addClass('active');
		jQuery('.payment-method-content').css('margin-bottom','10px');
		jQuery(".payment-methods .payment-group .payment-method .checkout").css("display","none");
		jQuery(".payment-methods .payment-group .payment-method #drpay-creditcard-form .checkout").css("display","block");		
		jQuery('.step-content').css('background','rgba(0,0,0,0)');
		if(window.checkoutConfig.quoteData.is_virtual){
			jQuery(".billing-address-details .action-edit-address").css("display","block");
		}else{			
			jQuery(".billing-address-details .action-edit-address").css("display","block");
			jQuery(".payment-method-billing-address .billing-address-same-as-shipping-block").css("display","block");
		}
	}	
</script>
