<?php 
$key = $this->helper('\Digitalriver\DrPay\Helper\Data')->getConfig('dr_settings/config/public_key');
$usr_locale = $this->helper('\Digitalriver\DrPay\Helper\Data')->getLocale();
$usr_locale_country = substr($usr_locale , 3, strrpos($usr_locale , '_'));
$usr_locale_language = substr($usr_locale , 0, strrpos($usr_locale , '_'));

#$order = $block->getOrder();
#$shippingAddress = $order->getShippingAddress(); 
#$usr_email = $this->helper('\Digitalriver\DrPay\Helper\Data')->getEmailAddress();

##$usr_email = $this->helper('\Digitalriver\DrPay\Helper\Data')->getEmailAddress();

## alert('<?php echo $usr_email
?>
<script type="text/javascript">
	var digitalriverjs = new DigitalRiver('<?php echo $key?>');

	function drCreditCardLoader(){
		if(typeof digitalriverjs != "undefined"){ //If url and key set in admin
			//loadScriptCard(jsUrl, function(){
		    //After append js set Your API Key and Start DigitalRiver.js
		    var drcreditcardjs = digitalriverjs;
			
			//Create your Card Number element
			var options = getDrCreditCardOptions('cardnumber');
			var cardNumber = drcreditcardjs.createElement('cardnumber', options);
			//Place the Card Number element within the container created above.
			cardNumber.mount('card-number');      
			//Create your Card Expiration element
			var options = getDrCreditCardOptions('cardexpiration');
			var cardExpiration = drcreditcardjs.createElement('cardexpiration', options);
			//Place the Card Expiration element within the container created above.
			cardExpiration.mount('card-expiration');
			//Create your Card Security Code element
			var options = getDrCreditCardOptions('cardcvv');
			var cardSecurityCode = drcreditcardjs.createElement('cardcvv', options);
			//Place the Card Security Code element within the container created above.
			cardSecurityCode.mount('card-security-code');    
			// Create a token or display an error when the form is submitted.
			var paymentForm = document.getElementById('drpay-creditcard-form');
				paymentForm.addEventListener('submit', function(event) {
				event.preventDefault(); 	
				var payload = {};
				jQuery.ajax({
                    type: 'POST',
                    showLoader: true, //use for display loader
                    url: BASE_URL + 'drpay/creditcard/savedrquote',
                    success: function (response) {
                        if (response.success) {
                            if(response.content.payload){
                                //once cart created get the payment source id
                                getCreditCardSourceId(drcreditcardjs, cardNumber, response.content.payload);
                            } else {
								document.getElementById('creditcard-message').innerHTML = ""; 
								document.getElementById('creditcard-message').innerHTML = "<?= $block->escapeJs($block->escapeHtml(__('Unable to process'))); ?>";
							}
                        }else{                            
							//Something went wrong, display the error message to the customer
							document.getElementById('creditcard-message').innerHTML = ""; 
							document.getElementById('creditcard-message').innerHTML = "<?= $block->escapeJs($block->escapeHtml(__('Unable to process'))); ?>";
                        }
                    }
                });				
			});
		
		
		
		taxIdentifier();
		
		}
	}
	function getCreditCardSourceId(drcreditcardjs, cardNumber, payload){
		drcreditcardjs.createSource(cardNumber,payload).then(function(result) {
			if(result.error) {
				document.getElementById('creditcard-message').innerHTML = ""; 
				document.getElementById('creditcard-message').innerHTML = "<?= $block->escapeJs($block->escapeHtml(__('Unable to process'))); ?>";
			} else {
				//Success!  You can now send the token to your server for use in downstream API calls.
				 var source = result.source;
				 var creditCardDetails = source.creditCard;
				 window.checkoutConfig.payment.drpay_creditcard.redirect_url = BASE_URL + 'drpay/payment/success';
				 if(source.id){
					jQuery.ajax({
						type: 'POST',
						url: BASE_URL + 'drpay/creditcard/savedrsource',
						data:{"source_id":source.id},
						showLoader: true, //use for display loader 
						success: function (response) {
							if (response.success) { 
								hideDrForm(creditCardDetails);
							}else{										
								document.getElementById('creditcard-message').innerHTML = ""; 
								document.getElementById('creditcard-message').innerHTML = "<?= $block->escapeJs($block->escapeHtml(__('Unable to process'))); ?>";
							}
						}
					});
				}
			}
		});
	}
	function getDrCreditCardOptions(element){		
		if(element == 'cardnumber'){
			mytext = '<?php echo $block->escapeJs($block->escapeHtml(__("Credit Card Number")));?>';
		}
		else if(element == 'cardexpiration'){
			mytext = '<?php echo $block->escapeJs($block->escapeHtml(__("Month/Year")));?>';
		}
		else{
			mytext = '<?php echo $block->escapeJs($block->escapeHtml(__("Card Security Code")));?>';
		}
		response = {
			classes: {
				base: "DRElement",
				complete: "complete",
				empty: "empty",
				focus: "focus",
				invalid: "invalid",
				webkitAutofill: "autofill"
	    	},
	        style: {
	        	base: {
	             color: "#555",
	             fontFamily: "Arial, Helvetica, sans-serif",
	             fontSize: "16px",
	             fontSmoothing: "auto",
	             fontVariant: "normal"
	             },
	             empty: {
	                 color: "#555"
	             },
	             complete: {
	                 color: "#555"
	             },
	             invalid: {
	                 color: "red"
	             }
	        }
		};
		response['placeholderText'] = mytext;
		return response;
	}	
	function displayDrForm(){
		jQuery(".payment-methods .payment-group .step-title").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .payment-method-title").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .details").css("display","inline-block");
		jQuery(".payment-methods .payment-group .payment-method .payment-logos").css("display","inline-block");
		jQuery(".payment-methods .payment-group .payment-method .payment-icon").css("display","inline-block"); 
		jQuery("#drpay-creditcard-form").css("display","block");
		jQuery("#payment-data").css("display","none");
		jQuery("#payment-data").removeClass('payment-active');
		jQuery(".payment-methods .payment-group .payment-method .payment-method-content .checkout").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .checkout").css("display","block"); 
		jQuery('.checkout-tabs .nav-pills li').removeClass('active');
		jQuery('.checkout-tabs .nav-pills li:nth-child(1)').addClass('active');
		jQuery('.step-content').css('background','none');
		jQuery('.payment-method-content').css('margin-bottom','10px');
		jQuery(".payment-methods .payment-group .payment-method .checkout").css("display","none");
		jQuery(".payment-methods .payment-group .payment-method #drpay-creditcard-form .checkout").css("display","block");
		if(window.checkoutConfig.quoteData.is_virtual){
			jQuery(".billing-address-details .action-edit-address").css("display","block");
		}else{
			jQuery(".billing-address-details .action-edit-address").css("display","block");
			jQuery(".payment-method-billing-address .billing-address-same-as-shipping-block").css("display","block");
		}
	} 
	function hideDrForm(creditCardDetails) { 
		if(creditCardDetails) { 
			var edit = '<?php echo $block->escapeJs($block->escapeHtml(__('Edit')));?>';
			var info = '<?php echo $block->escapeJs($block->escapeHtml(__('ending in')));?>';
			var title = "<div class='title'>"+jQuery(".payment-methods .payment-group .payment-method._active .payment-method-title .label span").html()+"</div>"; 
			var cartinfo = "<div class='card-info'>"+ creditCardDetails.brand + ' ' + info + ' '+ creditCardDetails.lastFourDigits+"</div>";
			var editlink = "<a class='payment-edit' href = 'javascript:void(0)' id='payment-edit' onclick='displayDrForm()'>"+edit+"</a>";
			jQuery("#payment-data").html(title+cartinfo+editlink);						
			jQuery("#payment-data").css("display","block");
			jQuery("#payment-data").addClass('payment-active');
			jQuery(".payment-methods .payment-group .step-title").css("display","none");
			jQuery(".payment-methods .payment-group .payment-method .payment-method-title").css("display","none");
			jQuery(".payment-methods .payment-group .payment-method .details").css("display","none");
			jQuery(".payment-methods .payment-group .payment-method .payment-logos").css("display","none");
			jQuery(".payment-methods .payment-group .payment-method .payment-icon").css("display","none");
			jQuery(".payment-methods .payment-group .payment-method .payment-method-instruction").css("display","none");
			jQuery("#drpay-creditcard-form").css("display","none");
			jQuery(".payment-methods .payment-group .payment-method .checkout").css("display","block");
			jQuery('.checkout-tabs .nav-pills li').removeClass('active');
			jQuery('.checkout-tabs .nav-pills li:nth-child(2)').addClass('active');
			jQuery('.step-content').css('background','#e6e6e6'); 
			if(window.checkoutConfig.quoteData.is_virtual){
				jQuery(".billing-address-details .action-edit-address").css("display","none");
			}else{
				jQuery(".billing-address-details .action-edit-address").css("display","none");
				jQuery(".payment-method-billing-address .billing-address-same-as-shipping-block").css("display","none");
			}
		}
	}
	
	function hideForm(){
		jQuery("#drpay_creditcard-content .payment-method-instruction").hide();
		jQuery("#drpay_creditcard-content #drpay-creditcard-form .payment-form-inner").hide();
	}
	function showForm(){
		jQuery("#drpay_creditcard-content .payment-method-instruction").show();
		jQuery("#drpay_creditcard-content #drpay-creditcard-form .payment-form-inner").show();
	}

	
	function taxIdentifier() {
let taxIdentifier;
           
            if (taxIdentifier) {
                taxIdentifier.destroy();
            }

            jQuery('#tax-id-container').html('');
            //setCountry(session.countryData.countryCode);
          //  set3dsCards(session.countryData.supports3ds);

          var  publicApiKey = '<?php echo $key?>'//$('#apiKey').val();
         var  locale = '<?php echo $usr_locale_country?>'//$('#locales').val();

            var country = '<?php echo $usr_locale_country?>';//$('#country').val();
            var usage = 'country';//$("input[type='radio'][name='usage']:checked").val();
          //  var savePayment = $('#savePayment').val();
          //  var showCompliance = $('#showCompliance').val();
          //  var customizeButton = $('#customizeButton').val();
          //  var customerType = $('#customerType').val();

            let options = {
                classes: {
                    base: "DRElement",
                    complete: "taxId-complete",
                    empty: "taxId-empty",
                    focus: "taxId-focus"
                },
                style: {
                    base: {
                        color: '#495057',
                        height: '35px',
                        fontSize: '1rem',
                        fontFamily: 'apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif',
                    },
                    complete: {
                        color: 'green',
                        ':-webkit-autofill': {
                            color: 'green'
                        }
                    }
                },
                taxIdentifier: {
					country: '<?php echo $usr_locale_country?>'
                }
            }



            digitalriverpayments = new DigitalRiver(publicApiKey, {
                "locale": '<?php echo $usr_locale_country?>'
            });

            taxIdentifier = digitalriverpayments.createElement('taxidentifier', options);
            taxIdentifier.mount('tax-id-container');

            taxIdentifier.on('ready', function (data) {
                if (!data.hasTaxIdentifier) {
                
                }
			//	var submitTaxIdBtn = '<div class=""><span class="submitDrTaxId">SUBMIT</span></div>';
			//	jQuery('#tax-id-container').append(submitTaxIdBtn);
  
            });

            taxIdentifier.on('change', function (data) {
             //   
            });



	}
	
	




</script>
