<?php $key = $this->helper('\Digitalriver\DrPay\Helper\Data')->getConfig('dr_settings/config/public_key');?>
<script type="text/javascript">
    function drDirectDebitLoader(){		
        if(typeof digitalriverjs != "undefined"){ //If url and key set in admin
            //loadScriptDebit(jsUrl, function(){
            // var script = document.createElement("script"); //Dynamically append the drDirectDebitjs
            // script.onload = function () {
            //After append js set Your API Key and Start DigitalRiver.js
            var drDirectDebitjs = digitalriverjs;
            // Create a token or display an error when the form is submitted.
            var paymentForm = document.getElementById('drpay-direct_debit-btn');
                paymentForm.addEventListener('click', function(event) {
                event.preventDefault();
                var payload = {};
                //After submit the DirectDebit details create the cart
                jQuery.ajax({
                    type: 'POST',
                    showLoader: true, //use for display loader
                    url: BASE_URL + 'drpay/directdebit/savedrquote',
                    success: function (response) {
                        if (response.success) {
                            if(response.content.payload){
                                //once cart created get the payment source id
                                getDirectDebitSourceId(drDirectDebitjs, response.content.payload);
                            } else {
								//Show Error Message
								document.getElementById('directdebit-message').innerHTML = "";
								document.getElementById('directdebit-message').innerHTML = "<?= $block->escapeJs($block->escapeHtml(__('Unable to process'))); ?>";
							}
                        }else{
                            //Show Error Message
                            document.getElementById('directdebit-message').innerHTML = "";
							document.getElementById('directdebit-message').innerHTML = "<?= $block->escapeJs($block->escapeHtml(__('Unable to process'))); ?>";
                        }
                    }
                });    
            });
        }
    }
    function getDirectDebitSourceId(drDirectDebitjs, payload){              
		drDirectDebitjs.createSource(payload).then(function(result) {
			document.getElementById('directdebit-message').innerHTML = '';
			if(result.error || result.source.state == "failed") {
				//Something went wrong, display the error message to the customer                        
				document.getElementById('directdebit-message').innerHTML = '<?php echo $block->escapeJs($block->escapeHtml(__("Error! Please check your address and try again.")));?>';
			} else {
				//Success!  You can now send the token to your server for use in downstream API calls.
				 var source = result.source;
				 var redirectUrl = source.redirect.redirectUrl; 
				 var edit = '<?php echo $block->escapeJs($block->escapeHtml(__('Edit')));?>';
				 window.checkoutConfig.payment.drpay_direct_debit.redirect_url = redirectUrl;
				 if(redirectUrl){
					var title = "<div class='title'>"+jQuery(".payment-methods .payment-group .payment-method._active .payment-method-title .label span").html()+"</div>";
					var editlink = "<a class='payment-edit' id='payment-edit-direct_debit' onclick='editDirectDebit()' href='javascript:void(0)'>"+edit+"</a>";
					console.log(title+editlink);
					jQuery("._active .payment-data").html(title+editlink);                        
					jQuery("._active .payment-data").css("display","block"); 
					jQuery("._active .payment-data").addClass('payment-active');
					jQuery(".payment-methods .payment-group .payment-method .payment-method-content .checkout").css("display","block");
					jQuery(".payment-methods .payment-group .payment-method._active .checkout").css("display","block"); 
					jQuery(".primary.payment-button").css("display","none");
					jQuery(".direct_debit-btn-first").css("display","none");
					jQuery(".direct_debit-btn-second").css("display","block");
					jQuery(".direct_debit-btn-second .checkout").css("display","block");
					jQuery(".payment-methods .payment-group .step-title").css("display","none");
					jQuery(".payment-method._active .payment-method-content .payment-method-note").css("display","none");
					jQuery(".payment-methods .payment-group .payment-method .payment-method-title").css("display","none");
					jQuery(".payment-methods .payment-group .payment-method .details").css("display","none");
					jQuery(".payment-methods .payment-group .payment-method .payment-logos").css("display","none");
					jQuery(".payment-methods .payment-group .payment-method .payment-icon").css("display","none");
					jQuery(".payment-methods .payment-group .payment-method .payment-method-instruction").css("display","none");
					jQuery("._active #payframe").css("display","none");
					jQuery('.checkout-tabs .nav-pills li').removeClass('active');
					jQuery('.checkout-tabs .nav-pills li:nth-child(2)').addClass('active');
					jQuery(".checkout-index-index h1.page-title .base").html('Checkout');
					jQuery('.step-content').css('background','#e6e6e6');
					jQuery('.payment-method-content').css('margin-bottom','50px');
					if(window.checkoutConfig.quoteData.is_virtual){
						jQuery(".billing-address-details .action-edit-address").css("display","none");
					}else{
						jQuery(".billing-address-details .action-edit-address").css("display","none");
						jQuery(".payment-method-billing-address .billing-address-same-as-shipping-block").css("display","none");
					}
				 }
			}
		});
    } 
    function editDirectDebit(){
        require(["jquery"], function ($) {
            $(".payment-methods .payment-group .step-title").css("display","block");
            $(".payment-data").removeClass('payment-active');
            $(".payment-methods .payment-group .payment-method .payment-method-title").css("display","block");
            $(".payment-methods .payment-group .payment-method .details").css("display","inline-block");
            $(".payment-methods .payment-group .payment-method .payment-logos").css("display","inline-block");
            $(".payment-methods .payment-group .payment-method .payment-icon").css("display","inline-block");
            $("._active #payframe").css("display","none");
            $("._active .payment-data").css("display","none");
            $(".payment-methods .payment-group .payment-method .payment-method-content .checkout").css("display","block");
            $(".payment-methods .payment-group .payment-method._active .checkout").css("display","none"); 
            $(".direct_debit-btn-first").css("display","block");
            $(".direct_debit-btn-second").css("display","none");
            $(".direct_debit-btn-second .checkout").css("display","none");            
            $(".payment-method._active .payment-method-content .payment-method-note").css("display","block"); 
            $(".primary.payment-button").css("display","block"); 
            $('.checkout-tabs .nav-pills li').removeClass('active');
            $('.checkout-tabs .nav-pills li:nth-child(1)').addClass('active');
            $('.step-content').css('background','none');
            $('.payment-method-content').css('margin-bottom','10px');    
			$(".payment-methods .payment-group .payment-method .checkout").css("display","none");
            if($('#applepay-element').length){ 
                document.getElementById('applepay-element').style.display = 'none';
            } 
			if(window.checkoutConfig.quoteData.is_virtual){
				$(".billing-address-details .action-edit-address").css("display","block");
			}else{				
				$(".billing-address-details .action-edit-address").css("display","block");
				$(".payment-method-billing-address .billing-address-same-as-shipping-block").css("display","block");
			}
        });        
    }    
</script>
